language: perl
perl:
  - "5.20"
  - "5.16"
env:
  - "HARNESS_OPTIONS=j1"
install:
  - "git config --global user.email dummy@example.com"
  - "git config --global user.name dummy"
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
notifications:
  email: false
